### PR TITLE
fix!: queries that panic should return `ack-err`

### LINKED ISSUE #85: If a query panics an error acknowledgement is not sent.
Example:

Let's say I want to query `GetCmdEstimateSwapExactAmountIn` from Osmosis, if you're querying a stableswap pool and enter more tokens than there are in a pool it will panic [Here](https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/pool-models/stableswap/amm.go#L118) this will not cause the query to panic and not return an error thus `async-icq` will not return an `ack-err`.

### PR DESCRIPTION
**Pull request by VitalyVolozhinov**
Closes #85

### CODE REVIEW

**Comment by dferendo** [comment]
idk why queries should panic in the first place but its a good pre-caution. lgtm

File: modules/async-icq/utils/cache_ctx.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+		return
+	case string:
+		ctx.Logger().Error("Recovering from (string) panic: " + e)
+	case runtime.Error:
+		ctx.Logger().Error("recovered (runtime.Error) panic: " + e.Error())
+	case error:
+		ctx.Logger().Error("recovered (error) panic: " + e.Error())
+	default:
+		ctx.Logger().Error("recovered (default) panic. Could not capture logs in ctx, see stdout")
+		fmt.Println("Recovering from panic ", recoveryError)
```
Comment (jtieri) [inline modules/async-icq/utils/cache_ctx.go:77]: is this line meant to be here still? since we already log an error here and this is not logged via the `Logger` it almost feels like debug output.

**Review by jtieri — CHANGES_REQUESTED** [review]
thanks for the contribution and sorry for the slow turnaround time on this one!

my one request would be to move `cache_ctx.go` into the `keeper` package since that is where code is being invoked at. then we can delete the `utils` package and make these functions unexported. my reasoning being that having packages named utils, helpers, common, etc. often feels like an anti-pattern and if the code is only being called in one place we can move the code there so it's more clear where it's utilized. it also allows us to encapsulate these functions so the exposed api is succinct.

**Comment by jtieri** [comment]
hey @VitalyVolozhinov wanted to ping you and see if there is an update on this? if i don't hear back from you I can address the couple nit picks that i mentioned and we can get this merged.

thanks again for your contributions!

File: modules/async-icq/utils/cache_ctx.go (hunk 1 above)
Comment (VitalyVolozhinov) [reply modules/async-icq/utils/cache_ctx.go]: Removed

**Comment by VitalyVolozhinov** [comment]
Thank you for reminding me about this! I've updated the code as per suggestion. Thank you!

**Comment by jtieri** [comment]
> Thank you for reminding me about this! I've updated the code as per suggestion. Thank you!

and thank you again for your contributions, they are greatly appreciated 🙂

**Comment by jtieri** [comment]
These changes should be included in the next minor releases of `async-icq` as they are state breaking.

**Review by jtieri — APPROVED** [review]
